matrix:
- name: Markdown
  expect_match: false
  aspell:
    mode: en
  dictionary:
    wordlists:
    - .spellcheck-wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
      - 'blockquote'
  sources:
  - '*.md'
  - 'doc/source/**/*.md'
  default_encoding: utf-8
