name: Continuous Integration
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
    paths-ignore:
      - '**/README.*'
      - 'doc/**'
      - '1.gocd.yml'
      - '.gitignore'

  push:
    branches:
      - master
    tags:
      - v**

jobs:
  defaults:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run tests for documentation
        run: |
          make test-doc
      - name: Build images
        run: |
          make init
          echo "" >> .env
          echo "# NOTE: try absolute path to current dir to get docker ro-mount to work" >> .env
          echo "DOCKER_MIGRID_ROOT=$PWD" >> .env
          make dockerbuild
      - name: Start services
        run: |
          make up
      - name: Run tests
        run: |
          make test
      - name: Read docker compose logs
        run: |
          make logs
      - name: Read migrid logs
        run: |
          tail -n +1 state/log/*
      - name: Stop services
        run: |
          make down
