name: Continuous Integration
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
    paths-ignore:
      - '**/README.*'
      - 'doc/**'
      - '1.gocd.yml'
      - '.gitignore'

  push:
    branches:
      - master
    tags:
      - v**

jobs:
  defaults:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run tests for documentation
        run: |
          make test-doc
      - name: Build images
        run: |
          make init
          echo "# NOTE: use absolute paths to current dir to get docker bind mounts to work" > ci.env
          echo "DOCKER_MIGRID_ROOT=$PWD" >> ci.env
          echo "" >> ci.env
          grep -E -v "DOCKER_MIGRID_ROOT=" .env >> ci.env
          rm -f .env
          mv ci.env .env
          make dockerbuild
      - name: Start services
        run: |
          grep -E "DOCKER_MIGRID_ROOT=|MIG_SYSTEM_RUN=" .env
          echo "NOTE: use sequential start here to make docker bind mounts behave"
          export COMPOSE_PARALLEL_LIMIT=1
          make up
      - name: Run tests
        run: |
          make test
      - name: Read docker compose logs
        run: |
          make logs
      - name: Read migrid logs
        run: |
          tail -n +1 state/log/*
      - name: Stop services
        run: |
          make down
