name: Spell Checking
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.py'
      - '**/*.yml'
      - '.gitignore'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v3
      - name: Check Spelling of docs
        uses: rojopolis/spellcheck-github-actions@0.36.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
